resolver: lts-16.0
packages:
  # - ch02/par-sudoku
  # - ch02/rpar
  # - ch03/strat
  # - ch03/kmeans
  - ch04/fwsparse
  # - ch04/pipeline
  - ch04/timetable
  - ch04/parinfer
  - ch05/repa-example
  # - ch05/fwdense
  # - ch05/rotateimage
  - ch06/accelerate-example
  # - ch06/fwaccel
  # - ch06/mandel
  - ch07/fork
  - ch07/reminders
  - ch07/mvar
  - ch07/logger
  - ch07/phonebook
  - ch07/chan
  - ch08/geturls
  - ch09/geturlscancel
  - ch09/modifytwo
  - ch09/chan3
  - ch09/timeout
  - ch09/catch-mask
  - ch10/windowman
  - ch10/tmvar
  - ch10/geturlsfirst
  - ch10/tchan
  - ch10/chanbench
  - ch11/async-geturls
  - ch11/timeout2
  - ch12/simple-server
  - ch12/chat
  - ch13/findseq
  - ch13/findpar
  - ch14/distrib-ping
  - ch14/distrib-chat
  - ch14/distrib-db
  - ch15/mvar
  - ch15/deadlock
  - ch15/threadperf

extra-deps:
  - github: AccelerateHS/accelerate
    commit: 170a2474705544bc4037f0ac2814a44edeb0790e
  - github: AccelerateHS/accelerate-llvm
    commit: 55ca08348002d69e54a146657cb15867582d0133
    subdirs:
      - accelerate-llvm
      - accelerate-llvm-ptx
  - github: tmcdonell/cuda
    commit: bf6efc8f9118caac91bde8c9535970f7ab645ead
  - github: davidsd/distributed-process
    commit: 144818f5174522ee4a027a4681ec047e0567c11b
  - distributed-process-simplelocalnet-0.2.4
  - distributed-static-0.3.9
  - network-2.6.3.6
  - network-multicast-0.2.0
  - network-transport-tcp-0.6.1
  - github: tmcdonell/nvvm
    commit: 219637eab3aab7275ce0a0c9b0e1855be912fe8a
  - repa-3.4.1.4
  - repa-devil-0.3.2.6

allow-newer: true

# extra-include-dirs:
#   - /usr/local/cuda-10.1/include
# extra-lib-dirs:
#   - /usr/local/cuda-10.1/lib64